### ISSUE TITLE
Feature: Allow displaying current values of specified VSCode settings in statusBarLabel

### ISSUE THREAD

**Issue by ev-dev** [wraith13/sysinfo-vscode#8]
Hey I really like many of your extensions they are great for fine tuning the editor!

I've been trying to find an extension that would let me display in the statusbar the current value of my VSCode's global/workspace `editor.fontSize`. 

I also use your Zoombar extension with a custom `zoomUnit` and swapped out the default keybindings for zoom in/out to use Zoombar for changing the UI size. I also have keybinding set for changing the editor font size and so I can easily adjust both the UI/text elements seperatly, it's quite nice especially for multiple monitors of different resolutions to quick adjust sizing.

As far as what sysinfo can display in the statusbar, it's a bit unclear in the README.md, but in the source code it seems like there isn't support for displaying any global/workspace settings values like `editor.fontSize`, but as I far as I understand it wouldn't be too difficult to include. I'll mess around with a fork for a bit and see what I can do and if you're available I could submit a PR as well :P 

Thanks again for all your cool extension work!

**Comment by wraith13** [comment]
Thank you for using my extensions!

I just released v2.5.1.

`$(symbol-color) ${settings:workbench.colorTheme}`
`$(text-size) ${settings:editor.fontSize}`
You can use specifications like these.

How about this?

**Comment by ev-dev** [comment]
Hey that's awesome! Exactly what I was hoping for, thanks for such a quick response and updates!
